# model parameters
latent_dimension: 128
input_image_size: [1,28,28] # MNIST Dataset is just greyscale --> in_channels == 1
hidden_dimensions: [32,64,128,256,512,1024] # The hidden Dimensions basically specify the numer of convolutional Layers where each element of the list specifies the number of filters (e.g. the output dimension)
max_pool: [False,False,False,False,False,False] # needs to have the same length as hidden_dimension and specifies per block if we use max pool
kernel_size_conv: (2,2)
stride_conv: (2,2)
learning_rate: 0.001
train_test_split: 0.8
kld_loss_weight: 0.00025
epochs: 40


# Some parameters what we want to log:
plot_reconstructed: True